# Generated by Django 5.0 on 2023-12-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bin", models.CharField(max_length=12, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Финансовая организация",
                "verbose_name_plural": "Финансовые организации",
            },
        ),
        migrations.CreateModel(
            name="Executive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("iin", models.CharField(max_length=12, unique=True)),
                ("position", models.CharField(max_length=255)),
                ("contact_phone", models.CharField(max_length=15)),
                ("contact_email", models.EmailField(max_length=254)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "financial_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance_app.financialorganization",
                    ),
                ),
            ],
        ),
    ]
