# Generated by Django 5.0 on 2023-12-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0003_alter_executive_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialorganization",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="bank_images/"),
        ),
    ]
