# Generated by Django 5.0 on 2023-12-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0004_financialorganization_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="executive",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="executive_images/"
            ),
        ),
    ]
