# Generated by Django 5.0 on 2023-12-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0005_executive_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executive",
            name="contact_email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="executive",
            name="contact_phone",
            field=models.CharField(max_length=15, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="executive",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Конец работы"),
        ),
        migrations.AlterField(
            model_name="executive",
            name="start_date",
            field=models.DateField(verbose_name="Начало работы"),
        ),
        migrations.AlterField(
            model_name="financialorganization",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Работает"),
        ),
        migrations.AlterField(
            model_name="financialorganization",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="financialorganization",
            name="bin",
            field=models.CharField(max_length=12, unique=True, verbose_name="БИН"),
        ),
        migrations.AlterField(
            model_name="financialorganization",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="financialorganization",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="bank_images/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="financialorganization",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название компании"),
        ),
        migrations.AlterField(
            model_name="financialorganization",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="financialorganization",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
    ]
